### ISSUE TITLE
Add `notify_none` to the default `ignore_messages_tagged_with` setting

### ISSUE THREAD

**Issue by moosingin3space** [s3rvac/weechat-notify-send#10]
The `wee-slack` script uses `notify_none` for all messages that shouldn't trigger notifications, so adding `notify_none` to the default ignore list will provide a better user experience.

**Comment by trygveaa** [comment]
Btw, `notify_none` isn't specific to wee-slack. It's documented at https://weechat.org/files/doc/stable/weechat_user.en.html#lines_tags.

**Comment by s3rvac** [comment]
Good idea, thanks! Done in 04032cd5e04b290f9830c545522a11c128152260.
