### ISSUE TITLE
Allow to pass desktop-entry to make possible to focus weechat

### ISSUE THREAD

**Issue by 3v1n0** [s3rvac/weechat-notify-send#14]
If you create a weechat.desktop file, the notification can include a "weechat" `desktop-entry` hint so that the desktop environment will allow to focus the window on click.

This is possible by just passing `--hint string:desktop-entry:weechat` to the notify-send

**Comment by s3rvac** [comment]
Implemented in commit e08713efdaa059f1bb66f5bec43423a79822e566. The code is based on unfinished PR #15.
