### ISSUE TITLE
timeout 0 does not work

### ISSUE THREAD

**Issue by sabactani** [s3rvac/weechat-notify-send#16]
I have changed timeout to 0 in order to notifications to not disappear, but they disappear anyway

**Comment by s3rvac** [comment]
Hi. Setting `timeout` to `0` works for me (the notification does not disappear). So, we will have to figure out why this parameter does not work for you. I have several questions:

* Can you try running `notify-send -t 0 test message` from a terminal? This is what `weechat-notify-send` internally uses to display notifications. If the message disappears, after how long does it disappear?
* What operating system and desktop environment do you use? As per [`notify-send` manual for Ubuntu](http://manpages.ubuntu.com/manpages/xenial/man1/notify-send.1.html), the timeout is ignored in Ubuntu's Notify OSD and GNOME Shell, so this may be the issue you are facing if you use Ubuntu.

**Comment by sabactani** [comment]
When I do notify-send -t 0 it does not disappear. And no, I'm not using ubuntu, I'm running gentoo. My notification daemon is dunst, but I tried it with notification-daemon but it did not work as well

Weechat-notify-send notifications disappear after 4-5 seconds even with timeout 0

**Comment by s3rvac** [comment]
I have asked a friend who runs Gentoo and setting the timeout to 0 in WeeChat works for her.

Anyway, before we delve into debugging, could you please once more check that you have `plugins.var.python.notify_send.timeout` set to `0`? You can set it via
```
/set plugins.var.python.notify_send.timeout "0"
```

**Comment by s3rvac** [comment]
Since there was no reaction, I assume that the above setting has fixed the problem for you, so I am closing this issue. If the problem persists, please re-open.
