### ISSUE TITLE
Release tags should be formatted in a consistent manner.

### ISSUE THREAD

**Issue by sudoforge** [s3rvac/weechat-notify-send#17]
# Summary

[Release tags][0] are inconsistently formatted:

- v0.3
- v0.3.1
- v0.3.2
- v0.3.3
- v0.4
- v0.6
- v0.7
- v0.8

It appears that you are dropping the [patch version][1] when creating the git tags, and github releases. This is less than ideal and could potentially create extra work for users who might be scripting around the version tag.

# Request

Please update the version strings for _both_ tags and GitHub Releases to be consistently formatted with a semver-compatible string.

[0]: https://github.com/s3rvac/weechat-notify-send/releases
[1]: https://semver.org/#summary

**Comment by s3rvac** [comment]
Thank you for the report. I do not think that release tags are inconsistently formatted. I simply omit a trailing `.0` whenever there would be one. This is common practice. I agree that it does not conform to SemVer, but to the best of my knowledge, I haven't written anywhere that the project follows SemVer.

To be honest, I do not feel like re-recreating all the tags and releases just to follow something that I have not promised to follow. Is there anything particular that really calls for using SemVer in this project?

**Comment by sudoforge** [comment]
@s3rvac Fair and correct points.

There is, as far as I am aware, not a major application for this, however, my particular use case was simply automating the build configuration file for this project for a particular package repository -- I had initially decided to simply add the trailing `.0` to make your version strings semver-compatible, however, decided against this as it would differ from the version string users saw on the release page.

**Comment by sudoforge** [comment]
I'll go ahead and close this request.
