### ISSUE TITLE
No notification on ubuntu with default configuration

### ISSUE THREAD

**Issue by ghost** [s3rvac/weechat-notify-send#21]
Hello,
I just followed the instructions to install the script and I don't receive any notification when I get a message.
I use Ubuntu with gnome3 and the default weechat and script configuration. q

**Comment by s3rvac** [comment]
Hi. First, let's see if the script is correctly loaded by running the following command within WeeChat:
```
/script list
```
Please, attach the output here. There should be `notify_send.py` in the list. If not, try to follow [installation steps](https://github.com/s3rvac/weechat-notify-send#installation) one more time.

If the script is loaded, let's see if `notify-send` works correctly outside of WeeChat. Try running the following command from a terminal:
```
notify-send test
```
This should show you a notification. If not, then you either do not have [`libnotify`](https://github.com/s3rvac/weechat-notify-send#requirements) in your system, or you do not have a notification daemon running, or there is something else wrong with your system.

If the script is loaded and you see a notification when running `notify-send` manually from a terminal, we will have to debug further. Let me know.

**Comment by ghost** [comment]
The script is loaded : 
```
Scripts loaded:
notify_send.py 0.9 (dev) (Sends highlight and message notifications through notify-send.)
```
And notifty-send  works correctly as well.

Thank you for your fast support.

**Comment by ghost** [comment]
Ahh after more testing, notify works with private message, but not in a public chan

**Comment by s3rvac** [comment]
Yes, this is [intended behavior](https://github.com/s3rvac/weechat-notify-send#weechat-notify-send):
> A WeeChat script that sends highlight and message notifications through notify-send.

So, by default, you will receive notifications only for highlights (e.g. when somebody mentions you) or for private conversations. From my experience, this is what most users want.

If you want to be notified about all messages in all channels, you can set the following [option](https://github.com/s3rvac/weechat-notify-send#options):
```
/set plugins.var.python.notify_send.notify_on_all_messages_in_buffers_that_match ".*"
```
Alternatively, if you only have a list of specific channels in which you want to be notified, you can set
```
/set plugins.var.python.notify_send.notify_on_all_messages_in_buffers "#channel1,#channel2"
```
See [this list](https://github.com/s3rvac/weechat-notify-send#options) for all the options.

Please, let me know if that worked for you so we can close the issue.

**Comment by ghost** [comment]
Thank you very much, that worked for me !
