### ISSUE TITLE
Notifications for current buffer not showing up

### ISSUE THREAD

**Issue by mirkojovanovic** [s3rvac/weechat-notify-send#22]
I have `notify_for_current_buffer` option set to `on`, however notifications for current buffer don't show up.

- weechat version: `2.7`
- script installed trough `/script`
- options set trough `/fset`
- running on Arch Linux

**Comment by s3rvac** [comment]
Hi. I think there is a misunderstanding about what the `notify_for_current_buffer` option does (maybe I have not chosen the best name for it). From the [docs](https://github.com/s3rvac/weechat-notify-send/#options):
> `notify_for_current_buffer`: Send also notifications for the currently active buffer. Default: `on`.

It means that notifications for the currently active buffer should not be suppressed. However, it does not mean that you will receive notifications for _all_ messages in the active buffer. Is that what you are looking for? To receive a notification for all messages in the currently active buffer?

**Comment by mirkojovanovic** [comment]
Yes, misunderstood the description. That's what I was looking for.

Seems useful to me. In case you don't want to recieve notifications from some channels, only if they are in active buffer. That way we could stay focused on the conversation of interest going, and check weechat only when neccessary, all while preventing overstimulation with so many notifications.

I love this script, thanks for writing it ;)

**Comment by s3rvac** [comment]
In commit 1c1092dbae74061976e83d44114faa5198e4603e, I have added a new config option `notify_on_all_messages_in_current_buffer`. Its default value is `off`. When set to `on`, you will receive a notification for all messages in the currently active buffer.

So, [grab the current `master` version of the script](https://raw.githubusercontent.com/s3rvac/weechat-notify-send/master/notify_send.py), set the option to `on`, and enjoy :wink:
