### ISSUE TITLE
Hide irc disconnect notifications when closing weechat

### ISSUE THREAD

**Issue by ajusa** [s3rvac/weechat-notify-send#23]
Hello!

I am wondering if there is anyway to hide the message that appears when weechat is closed. Specifically, the message looks like `irc: disconnected from server` and it appears in each channel I have joined. I did try using regex to only show notifications for messages that didn't start with "irc" but that didn't work either. Any ideas as to how to get around this? 

Thanks!

**Comment by s3rvac** [comment]
Hi. Would it be possible for you to:
1. Modify the script in the following way (add a debug print):
    ```diff
    diff --git a/notify_send.py b/notify_send.py
    index 37d73b9..2c91021 100644
    --- a/notify_send.py
    +++ b/notify_send.py
    @@ -275,6 +275,7 @@ def notification_should_be_sent(buffer, tags, nick, is_displayed, is_highlight,
     def notification_should_be_sent_disregarding_time(buffer, tags, nick,
                                                       is_displayed, is_highlight, message):
         """Should a notification be sent when not considering time?"""
    +    print(buffer, tags, nick, is_displayed, is_highlight, message)
         if not nick:
             # A nick is required to form a correct notification source/message.
         return False
    ```
2. Start WeeChat and connect to an IRC server (and join a channel).
3. Disconnect from the IRC server (without closing WeeChat, i.e. by `/disconnect`).
4. Post here the lines containing `disconnected from server` from the main WeeChat's buffer. I am mainly interested in the value of `tags`, but other values may be interesting as well.

**Comment by ajusa** [comment]
Sure! The output is 
```
12:39:25 weechat     | python: stdout/stderr (notify_send): 0xf15810 [''] - 1 0 irc: disconnected from server
4.  #home    │12:39:25 weechat     | python: stdout/stderr (notify_send): 0xf1bcb0 [''] - 1 0 irc: disconnected from server
             │12:39:25 weechat     | python: stdout/stderr (notify_send): 0xf27950 [''] - 1 0 irc: disconnected from server
             │12:39:25      im  -- | irc: disconnected from server
             │12:39:25 weechat     | python: stdout/stderr (notify_send): 0xd5fc20 [''] - 1 0 irc: disconnected from server
```
Thank you for the extremely clear debugging instructions. Also, when I reopen weechat and run `/debug tags` those messages have the no_notify tag on them (after loading the old messages). This issue only seems to manifest on disconnect.

**Comment by s3rvac** [comment]
Thanks for the quick output! Based on the output, we can see that the nick is just `-`. What I do is that I have the following configuration option set:
```
/set plugins.var.python.notify_send.ignore_nicks "-,--,-->"
```
It will prevent notifications for messages from nicks `-`, `--`, `-->`, which is usually just noise. When I wrote the script, I have not included these in the default options as I was not sure if people will want that. However, I will maybe change that. Anyway, I suggest giving this option a try :slightly_smiling_face:

**Comment by s3rvac** [comment]
Anyway, it is strange that these messages are not tagged with anything when they are received. WeeChat uses many tags (e.g. `irc_join`, `irc_quit`) which are by default filtered by the notification script (see the `ignore_messages_tagged_with` option). I would expect WeeChat to tag them, but this is sadly not the case.

**Comment by ajusa** [comment]
Ah okay, that makes sense. I had no idea that those characters could be nicks, thanks for sharing. I think you might want to consider having that be part of the default set of notifications to block, as people are probably more likely to close weechat than they are to disconnect from the internet. My issue is fixed though :smile:
