### ISSUE TITLE
The script fails to load due to the presence of the signal-weechat script

### ISSUE THREAD

**Issue by pinpox** [s3rvac/weechat-notify-send#24]
Hi, I get this error when running the plugin, any ideas?
```
14:51   ___       __         ______________        _____ 
14:51   __ |     / /___________  ____/__  /_______ __  /_
14:51   __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  __/
14:51   __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_  
14:51   ____/|__/  \___/\___/\____/  /_/ /_/\__,_/ \__/  
14:51 WeeChat 2.7.1 [compiled on Feb 20 2020 23:47:25]
14:51 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
14:51 perl scripts loaded: highmon, iset
14:51 python: stdout/stderr (?): Traceback (most recent call last):
14:51 python: stdout/stderr (?):   File "/home/binaryplease/.weechat/python/autoload/notify_send.py", line 34, in <module>
14:51 python: stdout/stderr (?):     import subprocess
14:51 python: stdout/stderr (?):   File "/usr/lib/python3.8/subprocess.py", line 49, in <module>
14:51 python: stdout/stderr (?):     import signal
14:51 python: stdout/stderr (?):   File "/home/binaryplease/.weechat/python/signal.py", line 536
14:51 python: stdout/stderr (?):     except OSError, e:
14:51 python: stdout/stderr (?):                   ^
14:51 python: stdout/stderr (?): SyntaxError: invalid syntax
14:51  !!!  python: unable to parse file "/home/binaryplease/.weechat/python/autoload/notify_send.py"
14:51 python scripts loaded: autojoin, autosort, colorize_nicks, facebook_rename, go, keepnick
14:51 script: 364 scripts for WeeChat 2.7.1
14:51 Plugins loaded: alias, buflist, charset, exec, fifo, fset, guile, irc, logger, lua, perl, python, relay, ruby, script, spell, tcl, trigger, xfer
```

**Comment by s3rvac** [comment]
Hi. Based on the provided output, I do not think that the issue is caused by [weechat-notify-send](https://github.com/s3rvac/weechat-notify-send). It seems to be caused by `/home/binaryplease/.weechat/python/signal.py`, which is apparently only for Python 2 (and you run Python 3.8):
```
14:51 python: stdout/stderr (?):   File "/home/binaryplease/.weechat/python/signal.py", line 536
14:51 python: stdout/stderr (?):     except OSError, e:
14:51 python: stdout/stderr (?):                   ^
14:51 python: stdout/stderr (?): SyntaxError: invalid syntax
```
I suggest reporting the error in [signal-weechat](https://github.com/thefinn93/signal-weechat/). If you think the issue is really in `weechat-notify-send`, I would like to ask you to remove the `signal` script and retry. If the issue appears after that, please re-open.

**Comment by s3rvac** [comment]
Additional note: WeeChat's [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path) seems to be set in such a way that when importing the standard [`signal`](https://docs.python.org/3/library/signal.html) module, [`weechat-signal`](https://github.com/thefinn93/signal-weechat) gets loaded instead:
```
14:51 python: stdout/stderr (?):   File "/home/binaryplease/.weechat/python/autoload/notify_send.py", line 34, in <module>
14:51 python: stdout/stderr (?):     import subprocess
14:51 python: stdout/stderr (?):   File "/usr/lib/python3.8/subprocess.py", line 49, in <module>
14:51 python: stdout/stderr (?):     import signal
14:51 python: stdout/stderr (?):   File "/home/binaryplease/.weechat/python/signal.py", line 536
14:51 python: stdout/stderr (?):     except OSError, e:
14:51 python: stdout/stderr (?):                   ^
```
My suggestion to the author of [signal-weechat](https://github.com/thefinn93/signal-weechat) would be to rename the script so it does not collide with the name of a standard module.

**Comment by s3rvac** [comment]
Mentioning the author of [signal-weechat](https://github.com/thefinn93/signal-weechat) here so they know about the name clash (see my comment above): @thefinn93.

**Comment by thefinn93** [comment]
signal-weechat is kind of unmaintained, and it looks like in this case not even compatible with the version of python you've got, so probably best to uninstall it. If you file an issue over at that repo, I can try to address all of this when i get that project back up off the ground @pinpox
