### ISSUE TITLE
Add the notification category

### ISSUE THREAD

**Issue by 3v1n0** [s3rvac/weechat-notify-send#27]
notify-send should be called with the `--category` (`-c`) flag set to `'im.received'`

**Comment by s3rvac** [comment]
Thanks for the report. From [here](https://unix.stackexchange.com/a/381093/42998):
```
im.received: A received instant message notification.
```
Makes sense. I will add that.

**Comment by s3rvac** [comment]
Added in commit cc701bdebdb1bf550e36aa8b13c59b47905db2dc.
