### ISSUE TITLE
Official scripts repo

### ISSUE THREAD

**Issue by danisztls** [s3rvac/weechat-notify-send#28]
I am using your script for awhile without issues. Had it installed from the AUR on Arch.

But recently I started using Weechat built-in script manager and I noticed `notify_send.py` isn't in the official [repo](https://weechat.org/scripts). Is there a reason?

**Comment by s3rvac** [comment]
Hi! This question has been answered and discussed in #1 and #4, so please see those two issues.

**Comment by danisztls** [comment]
I see @s3rvac. I don't see it as a problem. The names are close but not the same. One is `notify_send.PL`, the other `notify_send.PY`. Plugin settings will not conflict. And the former project is dead.  One can say that the later is the spiritual sucessor for the former. Have you tried to submit a [PR](https://github.com/weechat/scripts/pulls)?
