### ISSUE TITLE
transient=off not working

### ISSUE THREAD

**Issue by gour** [s3rvac/weechat-notify-send#29]
Hello!

Thank you very much for the only Weechat notification script which does work and helps me to migrate from Hechat to tui client!

I'm running mxlinux/xfce and would like to keep missed notification in the Xfce's notication bar, but just using

```
'transient': (
        'off',
        'When a notification expires or is dismissed, remove it from the '
        'notification bar.'
    ),
```

does not help and I had to do:

```
#631    return weechat.config_get_plugin('transient') == 'off'
```

Am I doing something wrong?

**Comment by s3rvac** [comment]
Hi. My guess is that you have changed the option only in the script, but not in WeeChat. The values in the script are used as the default ones when loading the script for the very first time. They are not meant to be edited. Instead, to change the value of an option, you have to run `/set plugins.var.python.notify_send.OPTION VALUE` within WeeChat.

Could you please try removing the custom changes from the `notify_send.py` file, starting WeeChat, disabling transient notifications by running `/set plugins.var.python.notify_send.transient off`, and see whether this fixes the issue?

**Comment by gour** [comment]
> Hi. My guess is that you have changed the option only in the script, but not in WeeChat.

Correct.

> The values in the script are used as the default ones when loading the script for the very first time. They are not meant to be edited. Instead, to change the value of an option, you have to run /set plugins.var.python.notify_send.OPTION VALUE within WeeChat.

Thank you for educating me! :smile: 

This solves it as well as #30 - it was the same issue. :disappointed:

**Comment by s3rvac** [comment]
Great! I am glad that both issues have been resolved. :slightly_smiling_face:

**Comment by s3rvac** [comment]
Solved by changing the `plugins.var.python.notify_send.transient` configuration option in WeeChat.
