### ISSUE TITLE
python: stdout/stderr (notify_send): Failed to send the notification via notify-send (reason: "CalledProcessError

### ISSUE THREAD

**Issue by KoraggKnightWolf** [s3rvac/weechat-notify-send#31]
Whenever a notification should be sent, it returns the following error, as in the title, I will output in here the entire string for the sake of completeness: 20:25:48 python: stdout/stderr (notify_send): Failed to send the notification via notify-send (reason: "CalledProcessError: Command '['notify-send', '--app-name', 'weechat', '--icon', '/usr/share/icons/hicolor/32x32/apps/weechat.png', '--hint', 'string:desktop-entry:weechat', '--expire-time', '5000', '--urgency', 'normal', '--category', 'im.received', '--', '#Skeleton', 'Testah: test test Skeleton  ']' returned non-zero exit status 1."). Ensure that you have notify-send installed in your system

This behavior seems odd as notify-send is installed on the system, and using a simple version manually, like: notify-send 'Test' 'Test Message' <--- works perfectly fine, showing the notification in the desktop and giving no errors whatsoever. 
The weechat.png file is also in the location given in the --icon file, so no missing icon or other component. 

I will do my best to provide the various components of the setup involved though: 

Weechat version: v3.6-73-g223eefef6

Tmux version for Weechat: tmux 3.2a

OS/Distro: Ubuntu 22.04

VNC server: tightvncserver (version shipped with Ubuntu 22.04)

Desktop Environment: Xfce4 (version shipped with Ubuntu 22.04)

Python version: Python 3.10.4

I hope this can aid in debugging the issue in some ways, and that they can be resolved soon, either by a change in the script if necessary, or that my setup can be adapted to work with the script properly. 

EDIT: Manually invoking the string that the script is trying to send generates a desktop notification without issue, making this problem even stranger: When I run the following command in a terminal on the vnc server, it gives the expected output without issue:
notify-send --app-name 'Weechat' --icon '/usr/share/icons/hicolor/32x32/apps/weechat.png' --hint 'string:desktop-entry:weechat' --expire-time '5000' --urgency 'normal' --category 'im.received' -- 'Koragg' 'testing notify-send'

ADDITION: seemingly only when ran on the vnc server itself is notify-send working, when running it through the ssh connection to the same vps it fails. Perhaps this is why it does not work with weechat on my setup, because it runs on the commandline? This behavior seems very strange, and perhaps this can aid others in the future with the same issue to resolve it.
additional error information 
Error calling StartServiceByName for org.freedesktop.Notifications: Process org.freedesktop.Notifications exited with status 1

While I am aware this may merely be an issue with my setup, it would be beneficial to receive aid in resolving them, as this script is very thorough in its configuration and customizability.

**Comment by s3rvac** [comment]
Hi, based on what you have reported, it indeed sounds like an issue with your specific setup. Could you please describe your setup in a greater detail? I am not sure that I understand it. More specifically, I am not sure where you run what. `notify-send` needs to be available on the system on which WeeChat is running, and it should produce notifications on the same system.

**Comment by KoraggKnightWolf** [comment]
No problem, I will try to explain it more clearly, I agree my description was convulated as I kept testing while trying to find out when it works and does not work. local will be my home laptop, and remote will be referring to the vps. the remote machine is the run running weechat and has notify-send installed. interestingly it seems that on the remote machine, which uses ubuntu, when I call notify-send when connected via ssh, or your script calls it, notify-send fails. however, on said remote machine, when I run notify-send manually (notify-send 'Test' 'test message') via a terminal in a vnc session, then it displays a desktop notification on said remote server (via the vnc session) just fine. 
This is the utterly confusing part, as notify-send on the remote machine works only when invoked manually in a vnc session, but not when run through an ssh session, or in weechat (through your script, or through the triggers example weechat itself gives). I am fairly sure it has to do with my setup, though I cannot pinpoint why in very specific situations, as hopefully more clearly outlined above, it does work, while generally it fails. I would very much wish to get your script working as it allows very fine-grained configuration for notifications. 
Thank you for taking the time to try and help me to get it working!

**Comment by s3rvac** [comment]
Thanks! I understand now. The issue is that notify-send on the VPS is unable to tunnel/forward notifications to your laptop via SSH. I see two options:
1. Run WeeChat on the laptop instead of on the VPS. If you need to be persistently connected to IRC, Jabber, etc., you can run [ZNC](https://wiki.znc.in/ZNC) on the VPS (allowing you to be persistently connected to IRC/Jabber/...) and connect to it via WeeChat running on the laptop. Notifications via weechat-notify-send will work correctly. This is the setup that I have been using.
2. Try to tunnel/forward notifications from the VPS to the laptop via SSH. Take a look [here](https://www.google.com/search?q=notify-send+via+ssh) for more guidance (there are several tutorials/HOWTOs). I have no experience with that.

**Comment by KoraggKnightWolf** [comment]
Thank you for aiding me in the debugging of my issue, it is now clear that the script is not at fault, but rather attempting to run it on a VPS. Hopefully if others should run into the same issue in the future, this issue can serve as a guideline for them as well to understand why it will not work.
Perhaps the README could include a hint that this script should only be used on a local machine, and not on a remote one? This could prevent people potentially running into the same situation as me.

For future generations: TL;DR: notify-send does not work by itself over SSH, even if it works over VNC, as both are different aspects/elements altogether, and one should run this script on a weechat which is on a local machine instead.
