### ISSUE TITLE
Great work.

### ISSUE THREAD

**Issue by SecHackLabs** [s3rvac/weechat-notify-send#4]
Hey s3rvac thanks for your work, you script is very funtionall and great. I hope that you never stop developing it. Unfortunately in the weechat scripts page is a script with the same name, but in perl. Thanks :)

**Comment by s3rvac** [comment]
Thank you for your kind words. I really appreciate that!

As for the WeeChat scripts page, I am aware of the situation, but I am afraid I do not have a solution. I have already covered this in #1. The reason why my script is not in there is that according to the [scripts page](https://weechat.org/scripts/add/), one should not submit scripts that:
- do exactly the same thing as already existing scripts, or
- have the same name as already existing scripts.

It is still possible to install my plugin manually, though. I hope this is not too inconvenient, as the installation has only two steps.

**Comment by raspbeguy** [comment]
Why don't you just rename your script? Your script is the only one I found to have the options I was looking.

**Comment by s3rvac** [comment]
I would rather not rename the script as its name has already been established and is used on the Internet. For my new projects, I will remember to choose a more unique name, though.

**Comment by raspbeguy** [comment]
Well, you could keep this name on your github, but change the name only for the weechat page.

**Comment by rawsp33d** [comment]
I agree it is easy to install as-is, but it's worth noting one huge advantage of having this on the weechat scripts page is it becomes very easy to update, in the same way as the other installed plugins.

If all of your scripts are installed in this way, you can execute a simple `/script upgrade` command, which in my case I set up to run periodically so my plugins all remain updated.
