### ISSUE TITLE
weechat-notify-send is a WeeChat script, not a plugin

### ISSUE THREAD

**Issue by sim642** [s3rvac/weechat-notify-send#8]
It is misleading for weechat-notify-send to call itself a WeeChat plugin because it is not one. WeeChat plugins are implemented in C and compiled. This, however, is a Python script, which is called a script in WeeChat.

It is important not to confuse the two because both are a thing in WeeChat but different. There are even different commands (`/plugin` vs `/script`) which need to be correctly used for things to work.

**Comment by s3rvac** [comment]
Thank you, I was not aware of that. I have updated the description, README, and source files to reflect WeeChat's nomenclature.
