### ISSUE TITLE
Not Showing Notification When Mentioned

### ISSUE THREAD

**Issue by iequahsh** [s3rvac/weechat-notify-send#9]
Hi,

I followed all the steps in the README, but I'm not able to notifications.

How do I fix this?

**Comment by s3rvac** [comment]
Hi. Could you please provide the following details?
* Do you get normal notifications when writing with someone (private messages via `/query`)? Or you do not get any notifications at all?
* If you do not get any notifications at all, do you have [libnotify](https://developer.gnome.org/libnotify/) in your system? If you do, do you get a notification when you run `notify-send testing message` from shell?
* Have you enabled the plugin after installation?
* Did you change any settings of weechat-notify-send?
* What WeeChat version do you use?
* What weechat-notify-send version do you use?
* What operating system do you use?

**Comment by iequahsh** [comment]
I've got it working. I simple had to install weechat-python. 

Thanks anyway
